name: build

on:
  push:
    branches:
    - main
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
        
