name: test

on:
  push:
    branches:
    - main
jobs:
   test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/
    steps:
      - uses: actions/checkout@v2
      - name: BUFFER
        run: B=42
      - name: export_buff
        run: export B
      - name: make
        run: make
